FROM python:3.10-slim

WORKDIR /app

COPY ./gemini_process /app/gemini_process
COPY ./utils__init__.py /app/utils__init__.py
# SUPPRIMER ou corriger la ligne suivante selon ta stratégie :
# COPY ./.env /app/.env

RUN pip install --no-cache-dir -r /app/gemini_process/requirements.txt

CMD ["python", "/app/gemini_process/main_gemini_pipeline.py"]
