name: Job_analytics_app
services:

  redis:
    image: redis:latest
    container_name: redis

    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  redis-commander:
    image: rediscommander/redis-commander
    container_name: rediscommander

    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
  data_extraction:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_data_extraction
    container_name: data_extraction_container
    volumes:
      - ./celery_app:/app/celery_app
      - ./data_extraction:/app/data_extraction
      - output:/app/data_extraction/scraping_output
      - logs:/app/data_extraction/Websites/log
    depends_on:
      - redis
    user: celery_user
    command: ["python", "/app/data_extraction/web_scrape.py"]
    environment:
    - PYTHONPATH=/app
    - CHROME_BIN=/app/data_extraction/Websites/chrome-linux64/chrome
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_worker
    container_name: celery_container
    command: ["celery", "-A", "celery_app.tasks", "worker", "--loglevel=info", "-E"]
    depends_on:
      - redis
    user: celery_user
    volumes:
      - ./celery_app:/app/celery_app
      - ./data_extraction:/app/data_extraction
      - output:/app/data_extraction/scraping_output
      - logs:/app/data_extraction/Websites/log
    environment:
    - PYTHONPATH=/app
    - CHROME_BIN=/app/data_extraction/Websites/chrome-linux64/chrome


  flower:

    image: app_worker
    container_name: flower_container
    ports:
      - "5555:5555"
    command: ["celery", "-A", "celery_app.tasks", "flower", "--port=5555","--loglevel=info"]
    user: celery_user
    volumes:
      - ./celery_app:/app/celery_app
    depends_on:
      - redis
      - celery
volumes:
  redis_data:
  logs:
  output:
