services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
    command: celery -A app.tasks.py worker -l INFO
