CACHE_CONFIG = {
    'CACHE_TYPE': 'null'
}

FEATURE_FLAGS = {
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True,
    "GENERIC_CHART_AXES": True,
    "ENABLE_ECHARTS": True,
}

