FROM python:3.10-slim

WORKDIR /app

# Copier les sources
COPY enrichment_requirements.txt .
RUN pip install --upgrade pip


# Installation des dépendances restantes
RUN pip install --no-cache-dir -r enrichment_requirements.txt
# Copie du reste des fichiers
COPY . .
# Commande de démarrage
CMD ["python", "/app/main_enrechissement_pipeline.py"]
