name: Lint on push and pull request
on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv pre-commit
          uv sync
      - name: Set up Git user
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Run pre-commit checks
        run: |
          pre-commit install
          pre-commit autoupdate
          pre-commit run --all-files  || (git add . && git commit -m "Fix formatting" && exit 0)
